apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.konghq.com
    chart: kong
    targetRevision: 2.46.0
    helm:
      helm:
        values: |
          env:
            database: "off"
          ingressController:
            enabled: true
          proxy:
            type: NodePort
          admin:
            enabled: true
            type: ClusterIP
          manager:
            enabled: true
            type: NodePort

  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true